name: Swift

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: |
        pod install --repo-update --clean-install --project-directory=Meeron/
        xcodebuild build -workspace Meeron/Meeron.xcworkspace -scheme Meeron
      
    #- name: Run tests
      #run: |
        #pod install --repo-update --clean-install --project-directory=Meeron/
        #xcodebuild clean test -workspace Meeron/Meeron.xcworkspace -scheme Meeron -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=latest'

